FROM node:12.18.2-alpine3.11 AS builder
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build


# Second Stage : Setup command to run your app using lightweight node image
FROM node:12.18.2-alpine3.11
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 80
CMD ["npm", "run", "start:prod"]